### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by EmanueleMinotto** [davedevelopment/twig-inflection#1]
Hi, I'm planning to write a Symfony 2 bundle wrapping this library.
Can you provide something like a `v1` release? It wuold be great for stable projects instead of adding the library to the root composer.json. :)
Thanks

**Comment by davedevelopment** [comment]
No problem! https://github.com/davedevelopment/twig-inflection/releases/tag/1.0

**Comment by EmanueleMinotto** [comment]
Great, thank you :) but [on packagist](https://packagist.org/packages/davedevelopment/twig-inflection) there's still the dev-master only

**Comment by davedevelopment** [comment]
@EmanueleMinotto fixed!
